// .ci/pipelines/main_branch.yaml
# Ana branch için daha sıkı kontrol
name: Main Branch Pipeline

on:
  push:
    branches: [main, master]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    
    - name: Install Dependencies
      run: flutter pub get
    
    - name: Full Test Suite
      run: |
        flutter test --coverage
        flutter test integration_test
    
    - name: Verify Coverage
      run: |
        minimum_coverage=80
        coverage=$(lcov --summary coverage/lcov.info 2>/dev/null | grep lines | awk '{print $2}' | sed 's/%//')
        if (( $(echo "$coverage < $minimum_coverage" | bc -l) )); then
          echo "❌ Coverage $coverage% is below minimum $minimum_coverage%"
          exit 1
        fi
        echo "✅ Coverage: $coverage%"
    
    - name: Build All Platforms
      run: |
        .ci/scripts/build_android.sh
        .ci/scripts/build_ios.sh
        .ci/scripts/build_web.sh
