name: 'Build Artifacts'
description: 'Build platform-specific artifacts'

inputs:
  platform:
    description: 'Platform to build (android, ios, web)'
    required: true
  
  flavor:
    description: 'Build flavor (dev, staging, production)'
    required: false
    default: 'production'

runs:
  using: 'composite'
  steps:
    - name: 🏗️ Build ${{ inputs.platform }} - ${{ inputs.flavor }}
      shell: bash
      run: |
        echo "Building for platform: ${{ inputs.platform }}"
        echo "Flavor: ${{ inputs.flavor }}"
        
        case "${{ inputs.platform }}" in
          android)
            flutter build apk --release --flavor ${{ inputs.flavor }} --split-per-abi
            ;;
          
          ios)
            flutter build ios --simulator --no-codesign --debug
            ;;
          
          web)
            flutter build web --release --web-renderer canvaskit
            ;;
          
          *)
            echo "Unknown platform: ${{ inputs.platform }}"
            exit 1
            ;;
        esac
    
    - name: ✅ Build Complete
      shell: bash
      run: echo "✅ ${{ inputs.platform }} build completed successfully"
