include: package:flutter_lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    todo: ignore
    unused_local_variable: error
    dead_code: error
    missing_required_param: error
    missing_return: error

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.g.dart"
    - "build/**"
    - ".dart_tool/**"
    - ".pub/**"
    - "**/generated/**"
    - "**/test/**"
    - "**/mock/**"

linter:
  rules:
    # === ERRORS ===
    avoid_print: true
    avoid_void_async: true
    dead_code: true
    empty_statements: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    unnecessary_null_checks: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true

    # === WARNINGS ===
    always_declare_return_types: true
    avoid_dynamic: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    empty_catches: true
    no_logic_in_create_state: true
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_this: true
