include: package:flutter_lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  exclude:
    - "**/*.g.dart"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - use_key_in_widget_constructors
