include: package:flutter_lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    todo: ignore
    unused_local_variable: error
    dead_code: error
    missing_required_param: error
    missing_return: error

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.g.dart"
    - "build/**"
    - ".dart_tool/**"
    - ".pub/**"
    - "**/generated/**"
    - "**/test/**"
    - "**/mock/**"

linter:
  rules:
    # === ERROR LEVEL ===
    avoid_print: error
    avoid_void_async: error
    dead_code: error
    empty_statements: error
    invariant_booleans: error
    no_duplicate_case_values: error
    prefer_void_to_null: error
    unnecessary_null_checks: error
    use_build_context_synchronously: error
    use_key_in_widget_constructors: error

    # === WARNING LEVEL ===
    always_declare_return_types: warning
    avoid_dynamic: warning
    avoid_empty_else: warning
    avoid_init_to_null: warning
    avoid_relative_lib_imports: warning
    cancel_subscriptions: warning
    close_sinks: warning
    directives_ordering: warning
    empty_catches: warning
    no_logic_in_create_state: warning
    prefer_const_constructors: warning
    prefer_final_locals: warning
    prefer_single_quotes: warning
    require_trailing_commas: warning
    unawaited_futures: warning
