name: 'Setup Flutter Environment'
description: 'Setup Flutter SDK with caching and dependencies'

inputs:
  flutter-version:
    description: 'Flutter SDK version'
    required: false
    default: '3.16.9'
  
  cache-key:
    description: 'Custom cache key suffix'
    required: false
    default: 'default'
  
  init-project:
    description: 'Initialize Flutter project if not exists'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: 📦 Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        cache: true
        cache-key: flutter-${{ inputs.cache-key }}-${{ runner.os }}
        cache-path: ${{ runner.tool_cache }}/flutter
    
    - name: 🏗️ Initialize Flutter Project
      if: ${{ inputs.init-project == 'true' }}
      shell: bash
      run: |
        echo "Initializing Flutter project structure..."
        
        # Geçici dizinde temiz Flutter projesi oluştur
        mkdir -p /tmp/flutter_init
        cd /tmp/flutter_init
        flutter create --org com.bazarigo --project-name bazarigo_mobile .
        cd -
        
        # Android klasörü yoksa oluştur
        if [ ! -d "android" ]; then
          echo "Copying Android structure..."
          cp -r /tmp/flutter_init/android .
        fi
        
        # iOS klasörü kontrolü - EKSİKSE VEYA BOZUKSA TAMAMEN YENİDEN OLUŞTUR
        if [ ! -d "ios" ] || [ ! -d "ios/Runner.xcodeproj" ]; then
          echo "iOS project missing or incomplete. Recreating..."
          rm -rf ios 2>/dev/null || true
          cp -r /tmp/flutter_init/ios .
          
          # Senin özel iOS dosyalarını koru (eğer varsa)
          if [ -f "ios/Runner/AppDelegate.swift" ]; then
            echo "Preserving custom AppDelegate.swift..."
            cp ios/Runner/AppDelegate.swift /tmp/AppDelegate.swift.backup
            cp /tmp/flutter_init/ios/Runner/AppDelegate.swift ios/Runner/
          fi
          
          if [ -f "ios/Runner/GoogleService-Info.plist" ]; then
            echo "Preserving GoogleService-Info.plist..."
            cp ios/Runner/GoogleService-Info.plist /tmp/GoogleService-Info.plist.backup
            cp /tmp/flutter_init/ios/Runner/GoogleService-Info.plist ios/Runner/
          fi
          
          if [ -f "ios/Runner/Info.plist" ]; then
            echo "Preserving Info.plist..."
            cp ios/Runner/Info.plist /tmp/Info.plist.backup
            cp /tmp/flutter_init/ios/Runner/Info.plist ios/Runner/
          fi
          
          # Yedekleri geri yükle
          if [ -f "/tmp/AppDelegate.swift.backup" ]; then
            cp /tmp/AppDelegate.swift.backup ios/Runner/AppDelegate.swift
          fi
          if [ -f "/tmp/GoogleService-Info.plist.backup" ]; then
            cp /tmp/GoogleService-Info.plist.backup ios/Runner/GoogleService-Info.plist
          fi
          if [ -f "/tmp/Info.plist.backup" ]; then
            cp /tmp/Info.plist.backup ios/Runner/Info.plist
          fi
        else
          echo "iOS project already exists and appears complete."
        fi
        
        # Web klasörü yoksa oluştur
        if [ ! -d "web" ]; then
          echo "Copying Web structure..."
          cp -r /tmp/flutter_init/web .
        fi
        
        # Lib ve test klasörleri (sadece yoksa)
        if [ ! -d "lib" ]; then
          cp -r /tmp/flutter_init/lib .
        fi
        
        if [ ! -d "test" ]; then
          cp -r /tmp/flutter_init/test .
        fi
        
        echo "✅ Project initialization complete"
    
    - name: 🔍 Flutter Doctor
      shell: bash
      run: flutter doctor -v
    
    - name: 📥 Get Dependencies
      shell: bash
      run: flutter pub get
    
    - name: ✅ Verify Installation
      shell: bash
      run: |
        flutter --version
        dart --version
